# Privacy Policy

This application is used to integrate Zabbix monitoring alerts with WhatsApp for internal operational purposes.

- **Data Collection**: We do not collect, store, or share any personal information. The app only processes server alerts generated by Zabbix.
- **Data Usage**: Alerts are transmitted to WhatsApp recipients to notify administrators of server status and issues.
- **Third Parties**: No data is shared with third parties outside of WhatsApp Business API, which is used solely for message delivery.
- **Security**: All communication between Zabbix and WhatsApp is secured using Meta’s official API and access tokens.
- **Contact**: For questions about this policy, please contact the system administrator of this monitoring setup.

Effective Date: December 2025
